### PR TITLE
Multiplatform port back to main

### LINKED ISSUE #1: Big clean-up
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#21  

Once all the core stuff at least sort of works, going to take a pass through and refactor a lot, so that it's more consistent and will be easier to develop going forward.

### LINKED ISSUE #4: Login Workflow
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#18  

Currently login is hardcoded. Do have a credentials cache now (would like to encrypt it at rest, currently plaintext), need to check if it works properly and finish the login workflow.

### LINKED ISSUE #5: Notifications backend
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#16  

null

### LINKED ISSUE #6: notifications
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#15  

null

### LINKED ISSUE #12: Navigation and making the buttons work
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#9  

null

### LINKED ISSUE #15: Feed timelines
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#6  

null

### LINKED ISSUE #17: Profile tab content (first pass)
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#3  

Still need the UI components for user lists.

### LINKED ISSUE #18: Main timeline view (Following)
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#2  

UI components done enough to start working on this

### LINKED ISSUE #19: Main timeline backend
From morpho-app created by [neema-orual](https://github.com/neema-orual): Radiant-Industries/morpho-app#1  

Have most of the UI and backend components to start putting the timeline views together now. Just need to build each one out

### PR DESCRIPTION
**Pull request by orual**
I think enough stuff is working in the Kotlin multi-platform version that it's time to do a merge back in.

### CODE REVIEW

**Comment by ghost** [comment]
@orual will finish looking this over in the afternoon. gonna wait on the merge until you check that last commit, if it's no good we can just revert it and proceed for now, then revisit

**Comment by orual** [comment]
Had to make a couple changes to your commit bc there were some type issues missed writing it on web, but it doesn't break anything at least. Still need to write an offline test for it.

**Review by ghost — APPROVED** [review]
test cases are passing so i think we are good to go

**Comment by orual** [comment]
Awesome

**Pull request merged**
